name: CI/CD Fullstack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install backend dependencies
        working-directory: ./AV2-backend-Fullstack
        run: npm install

      - name: Run Jest tests
        working-directory: ./AV2-backend-Fullstack
        run: npm test -- --runInBand

  build-and-push:
    name: Build & Push Docker Images
    needs: test-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login Docker
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build backend
      - name: Build backend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-backend:latest \
            ./AV2-backend-Fullstack

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-backend:latest

      # Build frontend (com ARG VITE_BACKEND_URL)
      - name: Build frontend image
        run: |
          docker build \
            --build-arg VITE_BACKEND_URL=${{ secrets.FRONTEND_BACKEND_URL }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-frontend:latest \
            ./AV2-Fullstack-Frontend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-frontend:latest